version: "3"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    networks:
      - app-tier
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    networks:
      - app-tier
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - '27017:27017'
    networks:
      - app-tier
    environment:
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=testtest
      - MONGODB_DATABASE=testdb
      - ALLOW_EMPTY_PASSWORD=yes
  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    ports:
      - '9221:9221'
    networks:
      - app-tier
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9201